// Generated by Wrangler on Mon May 20 2024 19:56:29 GMT-0400 (Eastern Daylight Saving Time)
// by running `wrangler types`

interface Env {
	SNAPSHOTS: R2Bucket;
	DB: D1Database;
	STATIONS_CURRENT: Fetcher;
}
